name: Run Azure Login with OIDC and Automatic Build & Deploy to AKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Run Azure CLI Command
        run: az account show

      - name: Verify ACR Existence
        run: az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY }} || echo "ACR not found"

      - name: Login to Azure Container Registry (ACR)
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Install Make
        run: sudo apt update && sudo apt install make -y

      # - name: Install Docker
      #   run: sudo apt update && sudo apt install docker -y

      - name: Build & Push Docker Image
        run: make docker-build ./ && make docker-push ./
        # working-directory: ./

      - name: Set Up Kubernetes (kubectl)
        uses: azure/setup-kubectl@v1
        with:
          version: latest

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_AKS_CLUSTER }}

      - name: Deploy to AKS
        run: make deploy
